main/urls.py
from django.urls import path

from .views import other_page
from .views import index
from .views import SiteModelLoginView
from .views import profile
from .views import SiteModelLogoutView
from .views import ChangeUserInfoView

app_name = 'main'
urlpatterns = [ 
	path('<str:page>/', other_page, name='other'),
	path('', index, name='index'),
	path('accounts/login/', SiteModelLoginView.as_view(), name='login'),
	path('accounts/profile/', profile, name='profile'),
	path('accounts/logout/', SiteModelLogoutView.as_view(), name='logout'),
	path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
]

sitemodel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),

]

main/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
	is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Did you get activation?')
	send_messages = models.BooleanField(default=True, verbose_name='Send notifications about new comments?')
	
	class Meta(AbstractUser.Meta):
		pass

main/forms.py
from django import forms

from .models import AdvUser

class ChangeUserInfoForm(forms.ModelForm):
	email = forms.EmailField(required=True, label='Email')

	class Meta:
		model = AdvUser
		fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

main/views.py
from django.shortcuts import render

from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from .models import AdvUser
from .forms import ChangeUserInfoForm

class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	model = AdvUser
	template_name = 'main/change_user_info.html'
	form_class = ChangeUserInfoForm
	success_url = reverse_lazy('main:profile')
	success_message = 'You info changed'

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk 
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset = None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk=self.user_id)


class SiteModelLogoutView(LoginRequiredMixin, LogoutView):
	template_name = 'main/logout.html'


@login_required
def profile(request):
	return render(request, 'main/profile.html')

class SiteModelLoginView(LoginView):
	template_name = 'main/login.html'


def other_page(request, page):
	try:
		template = get_template('main/' + page + '.html')
	except TemplateDoesNotExist:
		raise Http404
	return HttpResponse(template.render(request=request))

def index(request):
	return render(request, 'main/index.html')

main/templates/layout/basic.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    
    {% load static %}
    <link rel="stylesheet" type="text/css" href=" {% static 'main/css/style.css' %}">

    <title>{% block title %} Home {% endblock %} - Slibrary</title>
  </head>

  <body>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'main/img/favicon2.png' %}">

    <nav class="shadow-navbar site-header sticky-top py-1" style="height: 80px;">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="{% url 'main:index' %}" aria-label="Product">
          <img src="{% static 'main/img/logo_ghost.jpg' %}" style="height: 50px;">
        </a>
        
        <h1 class="logo-text my-auto ml-3" href="{% url 'main:index' %}">GHOST</h1>
        <div class="ml-auto my-auto">
          <a class="btn menu_button " href="{% url 'main:index' %}">Home</a>
          <a class="btn menu_button " href="{% url 'main:other' page='sales' %}">Sales</a>
          <a class="btn menu_button " href="{% url 'main:other' page='news' %}">News</a>
          <a class="btn menu_button " href="{% url 'main:other' page='about' %}">About Us</a>
          <a class="menu_button" href="{% url 'main:other' page='favorites' %}">
            <svg width="20" height="20" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
            </svg>
          </a>

          <a class="menu_button">
            <svg width="20" height="20" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
              <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
            </svg>
          </a>
          {% if user.is_authenticated %}
          <a class=""href="{% url 'main:profile' %}" >
            <svg width="25" height="25" viewBox="0 0 16 16" class="bi bi-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            </svg>
            You already entered
          </a>
          {% else %}
          <a class="" href="{% url 'main:login' %}" >
            <svg width="25" height="25" viewBox="0 0 16 16" class="bi bi-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            </svg>
            Log in
          </a>
          {% endif %}
          <a href="{% url 'main:logout' %}">Exit</a>
          <a href="{% url 'main:profile_change' %}">Change</a>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer-area footer-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Us</h6>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam fugiat deserunt aperiam, ab illum ducimus.</p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Us</h6>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam fugiat deserunt aperiam, ab illum ducimus.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Us</h6>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam fugiat deserunt aperiam, ab illum ducimus.</p>
            </div>
          </div>
          <div class="col-lg-2 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Us</h6>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam fugiat deserunt aperiam, ab illum ducimus.</p>
            </div>  
          </div>
        </div>
        <div class="footer-copyright d-flex justify-content-center align-items-center flex-wrap">
          <p class="footer-text m-0">
            Copyright ©2020 | GHOST | All rights reserved 
          </p>
        </div>
      </div>
    </footer>

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %}About us{% endblock %}

{% block content %}

{% load static %}
<section class="background-area section-for-breadcrumbs">
	<div class="container">
		<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
			<div class="col-first">
				<h1>Contact</h1>
				<nav aria-label="d-flex align-items-center">
				  <ol class="breadcrumb">
				    <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Home</a></li>
				    <li class="breadcrumb-item active" aria-current="page">About Us</li>
				  </ol>
				</nav>
			</div>
		</div>
		
	</div>
	
</section>

<section>
	<div class="container">
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae reprehenderit distinctio unde consectetur, atque praesentium dolores asperiores ullam dignissimos voluptatem aliquid labore ex quae vero quas ipsum ratione vel veniam voluptas minus doloribus ducimus eveniet quaerat! Cum, nam minima doloribus repellat vel ipsa inventore consequatur similique vero harum, odit unde molestiae, optio accusantium dignissimos facere? Dolorem laboriosam sit est eaque praesentium, itaque iure asperiores omnis et quidem fuga officiis consequuntur quibusdam repellendus minima, maiores ipsa nisi molestias nihil temporibus. Numquam voluptatibus consequuntur, labore eligendi expedita non sunt distinctio corporis blanditiis? Libero, facilis, reiciendis. Quisquam, doloremque nobis tempore omnis delectus quibusdam?</p>
	</div>
</section>
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load widget_tweaks %}

{% block titile %}Edit{% endblock %}

{% block content %}
<div class="container">
  <div class="col-lg-6">
    <h2>Edit your information</h2>
    <form method="post">
      {% csrf_token %}

      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field|add_class:'form-control' }}
          {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}

      <div class="form-group">
        <button type="submit" class="btn btn-success">
          <span class="glyphicon glyphicon-ok"></span> Save
        </button>
        <a href="{% url 'main:index' %}" class="btn btn-default">Cancel</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

main/templates/main/favorites.html
{% extends "layout/basic.html" %}

{% block title %}Favorites{% endblock %}

{% block content %}

{% load static %}
<div class="container">
	<div class="jumbotron">
	  <h1 class="display-4">Hello, world!</h1>
	  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
	  <hr class="my-4">
	  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
	  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
	</div>

	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Home</a></li>
	    <li class="breadcrumb-item active" aria-current="page">Favorites</li>
	  </ol>
	</nav>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae reprehenderit distinctio unde consectetur, atque praesentium dolores asperiores ullam dignissimos voluptatem aliquid labore ex quae vero quas ipsum ratione vel veniam voluptas minus doloribus ducimus eveniet quaerat! Cum, nam minima doloribus repellat vel ipsa inventore consequatur similique vero harum, odit unde molestiae, optio accusantium dignissimos facere? Dolorem laboriosam sit est eaque praesentium, itaque iure asperiores omnis et quidem fuga officiis consequuntur quibusdam repellendus minima, maiores ipsa nisi molestias nihil temporibus. Numquam voluptatibus consequuntur, labore eligendi expedita non sunt distinctio corporis blanditiis? Libero, facilis, reiciendis. Quisquam, doloremque nobis tempore omnis delectus quibusdam?</p>
</div>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}

{% load static %}

    <div class="background-area photoground">
      <!-- Bootstrap 4 -->
      <div class="container">
        <div id="carousel" class="carousel slide" data-ride="carousel" style="height: 862px;">
          <!-- Индикаторы -->
          <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="img-fluid" style="height: auto;" src="{% static '/main/img/car_1.png' %}" alt="...">
            </div>
            <div class="carousel-item">
              <img class="img-fluid" style="height: 820px;" src="{% static '/main/img/car_2.png' %}" alt="...">
            </div>
            <div class="carousel-item">
               <img class="img-fluid" style="height: 820px;" src="{% static '/main/img/car_3.png' %}" alt="...">
            </div>
          </div>
          <!-- Элементы управления -->
          <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Предыдущий</span>
          </a>
          <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Следующий</span>
          </a>
        </div>
      </div>
    </div>

      
  <section class="section-middle-1">  
    <div class="container">
      <div class="row shadow-inner-section-middle-1">

        <div class="col-lg-3">
          <div class="box-inner-section-middle-1">
            <div class="img-middle-1">
              <img src="{% static 'main/img/box_middle_3.png' %}" alt="">
            </div>

            <h6>Free Delivery</h6>
            <p>Free Shipping on all order</p>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="box-inner-section-middle-1">
            <div class="img-middle-1">
              <img src="{% static 'main/img/box_middle_3.png' %}" alt="">
            </div>
            <h6>Return Policy</h6>
            <p>Free Shipping on all order</p>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="box-inner-section-middle-1">
            <div class="img-middle-1">
              <img src="{% static 'main/img/box_middle_3.png' %}" alt="">
            </div>
            <h6>24/7 Support</h6>
            <p>Free Shipping on all order</p>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="" style="text-align: center;">
            <div class="img-middle-1" style="margin-bottom: 20px;">
              <img src="{% static 'main/img/box_middle_3.png' %}" alt="">
            </div>
            <h6>Secure Payment</h6>
            <p>Free Shipping on all order</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="section-photo">
    <div class="container" style="margin-bottom: 50px;">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="row">
            <div class="col-lg-4">
              <div class="box_photo">
                <img src="{% static '/main/img/box_photo_1.jpg' %}" class="img-fluid w-100">
              </div>
            </div>
            <div class="col-lg-8">
              <div class="box_photo">
                <img src="{% static '/main/img/box_photo_3.jpg' %}" class="img-fluid w-100">
              </div>
            </div>
            <div class="col-lg-8">
              <div class="box_photo">
                <img src="{% static '/main/img/box_photo_3.jpg' %}" class="img-fluid w-100">
              </div>
            </div>
            <div class="col-lg-4">
              <div class="box_photo">
                <img src="{% static '/main/img/box_photo_2.jpg' %}" class="img-fluid w-100">
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="box_photo">
            <img src="{% static '/main/img/111.jpg' %}" class="img-fluid w-10">
          </div>
        </div>
      </div>
    </div>
  </section>



  <section class="card-block">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-6 mb-3" style="text-align: center;">
          <h1 class="logo-text">Lorem ipsum.</h1>
          <p class="logo-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi quo quis, architecto quos iusto excepturi maxime inventore tenetur. Minus, ipsa?</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
        <div class="col-lg-3 card-row-margin">
            <a class="link-card" href="">
              <div class="card-row-margin">
                <img class="img-fluid w-100" src="http://127.0.0.1:8000/static/main/img/card_1.jpeg">
              </div>
              <p style="color: #2e2e2e;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, inventore.
              </p>
              <p class="price">
                <span style="text-decoration: line-through;">$232</span>
                <span class="price-sale">$230</span>
              </p>
              <div class="only-sale">-67%</div>
            </a>
        </div>
      <a class="primary-btn mx-auto mb-5" href="{% url 'main:other' page='sales' %}">
      	Next
      </a>
    </div>
  </section>

{% endblock %} 

main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}

<h2>Login</h2>

{% if user.is_authenticated %}
  <p>You already entered</p>

{% else %}
<div class="container">
  <form method="post">
    {% csrf_token %}


    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
      </div>
    {% endfor %}

    <div class="form-group">
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-ok"></span> Log in
      </button>
      <a href="{% url 'main:index' %}" class="btn btn-default">Cancel</a>
    </div>
  </form>
</div>

{% endif %}

{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
<p>Logged out!</p>  

<a href="{% url 'main:login'%}">Click here to login again.</a>
{% endblock %}

main/templates/main/news.html
news.html

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load widget_tweaks %}

{% block title %}Profile{% endblock %}

{% block content %}

<h2>User: {{ user.username }}</h2>

{% endblock %}

main/templates/main/sales.html
{% extends "layout/basic.html" %}

{% block title %}Sales{% endblock %}

{% block content %}

{% load static %}
<div class="container">
	<div class="jumbotron">
	  <h1 class="display-4">Hello, world!</h1>
	  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
	  <hr class="my-4">
	  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
	  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
	</div>

	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Home</a></li>
	    <li class="breadcrumb-item active" aria-current="page">Sales</li>
	  </ol>
	</nav>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae reprehenderit distinctio unde consectetur, atque praesentium dolores asperiores ullam dignissimos voluptatem aliquid labore ex quae vero quas ipsum ratione vel veniam voluptas minus doloribus ducimus eveniet quaerat! Cum, nam minima doloribus repellat vel ipsa inventore consequatur similique vero harum, odit unde molestiae, optio accusantium dignissimos facere? Dolorem laboriosam sit est eaque praesentium, itaque iure asperiores omnis et quidem fuga officiis consequuntur quibusdam repellendus minima, maiores ipsa nisi molestias nihil temporibus. Numquam voluptatibus consequuntur, labore eligendi expedita non sunt distinctio corporis blanditiis? Libero, facilis, reiciendis. Quisquam, doloremque nobis tempore omnis delectus quibusdam?</p>
</div>
{% endblock %}